<script setup>
import { computed, ref } from 'vue'

const props = defineProps({ planView: { type: Object, required: true } })
const openDietDays = ref(new Set(['1']))
const openExerciseDays = ref(new Set(['1']))

const statusLabels = {
  ACTIVE: '已确认', ACTIVE_RECALCULATED: '已重新计算', PROVISIONAL: '候选，待复核', UNAVAILABLE: '当前暂无法形成精确目标',
  EXACT_ACTIVE: '精确目标已确认', EXACT_PROVISIONAL_REVIEW: '精确候选，需审核后发布', STRUCTURE_ONLY: '当前仅提供结构化方案',
  FULL: '完整', PASS: '通过', FAIL: '需复核', PENDING: '待确认', SOURCE_PENDING: '来源待确认', NEEDS_SOURCE_RECALC: '来源待确认',
  NO_APPROVED_STRUCTURED_REPLACEMENT: '当前无已审核结构化替换', NOT_MATERIALIZED: '尚未形成执行版本', NOT_SCHEDULED: '本周不安排', NOT_APPLICABLE: '不适用', NOT_DUE: '尚未到复评时间', MISSING: '暂无数据', BLOCKED: '暂不可发布', DRAFT: '草稿',
  AI_GENERATED_PENDING_REVIEW: '待医护审核', IN_REVIEW: '审核中', APPROVED: '已审核', APPROVED_PENDING_MDT_ACTIVATION: '已审核，尚未满足发布条件', APPROVED_PENDING_PUBLISH: '已审核，尚未满足发布条件', READY_TO_PUBLISH: '已满足发布条件', PUBLISHED: '已发布', RETURNED: '已退回修改', AVAILABLE: '已形成', SCHEDULED: '已安排', NOT_REVIEWED: '未审核', NONE: '无', none: '无', YELLOW: '需加强复核', GREEN: '常规管理', RED: '需暂停并升级处理', yellow: '需加强复核', green: '常规管理', red: '需暂停并升级处理',
}
const reasonLabels = { COMPLEXITY_EXECUTION_REVIEW: '执行复杂度需医护关注', MUSCLE_FUNCTION_RISK_REVIEW: '肌肉/功能风险需医护关注', NUTRITION_RISK_REVIEW: '营养风险需医护关注', OPTIONAL_SKILL_LEARNING_DEFERRED_FOR_COMPLEXITY: '考虑当前执行负担，本周暂缓该技能学习', FUNCTIONAL_ACTIVITY_SOURCE_UNAVAILABLE: '功能活动来源暂不可用' }
const goalLabels = { overall_goal: '总体目标', weight_goal: '体重目标', body_fat_goal: '体脂目标', waist_goal: '腰围目标', muscle_goal: '肌肉目标', functional_goal: '功能目标', metabolic_goals: '代谢目标', surgery_preparation_goal: '术前准备目标' }
const enumLabels = { STANDARD_FAT_LOSS: '标准减脂目标', STOP_WEIGHT_LOSS: '停止继续减重', METABOLIC_CONTROL: '代谢控制', PREOPERATIVE_PREPARATION: '术前准备', SKILL_LEARNING: '术前技能学习', AIRWAY_CLEARANCE: '气道清除训练', NOT_SELECTED: '本周暂不安排', breakfast: '早餐', lunch: '午餐', dinner: '晚餐', snack: '加餐' }

const view = computed(() => props.planView || {})
const moduleValue = (key) => view.value[key] || {}
const displayLabel = (value, fallback = '—') => { if (value === null || value === undefined || value === '') return fallback; if (typeof value === 'object') return fallback; const key = String(value); return reasonLabels[key] || enumLabels[key] || statusLabels[key] || key }
const statusText = (module) => module?.display_status ? displayLabel(module.display_status, '待确认') : displayLabel(module?.status, '待确认')
const reviewStatusText = (module) => displayLabel(module?.review_status || module?.plan_status, '未审核')
const publicationStatusText = (value) => String(value || '').toUpperCase() === 'PASS' ? '发布条件已满足' : String(value || '').toUpperCase() === 'BLOCKED' ? '暂不可发布' : displayLabel(value, '待确认')
const humanizeText = (value) => String(value).replace(/SpO₂异常|SpO2异常/g, '血氧异常').replace(/PROVISIONAL/g, '候选').replace(/UNAVAILABLE/g, '暂无法形成精确目标').replace(/ACTIVE/g, '已确认').replace(/STRUCTURE_ONLY/g, '结构化方案').replace(/PUBLICATION_BLOCKED/g, '发布阻断')
const valueText = (value, fallback = '—') => { if (value === null || value === undefined || value === '') return fallback; if (Array.isArray(value)) return value.length ? value.map((item) => typeof item === 'object' ? '' : humanizeText(displayLabel(item, ''))).filter(Boolean).join('、') : fallback; if (typeof value === 'object') return fallback; return humanizeText(displayLabel(value, fallback)) }
const reasonText = (module) => valueText(module?.reason || module?.display_reason, '')
const goalEntries = (items) => Object.keys(goalLabels).map((key) => ({ key, label: goalLabels[key], value: items?.[key] })).filter((item) => item.value !== null && item.value !== undefined && item.value !== '')
const nutritionText = (nutrition, fallback = '当前仅提供结构化方案') => { if (!nutrition || typeof nutrition !== 'object') return fallback; const values = [nutrition.kcal != null ? `能量 ${nutrition.kcal} kcal` : '', nutrition.protein_g != null ? `蛋白 ${nutrition.protein_g} g` : '', nutrition.carbohydrate_g != null ? `碳水 ${nutrition.carbohydrate_g} g` : '', nutrition.fat_g != null ? `脂肪 ${nutrition.fat_g} g` : ''].filter(Boolean); return values.join(' · ') || fallback }
const plannedNutritionText = (meal) => nutritionText(meal?.planned_nutrition)
const itemNutritionText = (item) => item?.planned_nutrition ? nutritionText(item.planned_nutrition, '') : ''
const normalizeDayKey = (day, index) => String(day?.day ?? index + 1)
const isDietDayOpen = (key) => openDietDays.value.has(key)
const isExerciseDayOpen = (key) => openExerciseDays.value.has(key)
const toggleDay = (days, key) => { const next = new Set(days.value); if (next.has(key)) next.delete(key); else next.add(key); days.value = next }
const toggleDietDay = (key) => toggleDay(openDietDays, key)
const toggleExerciseDay = (key) => toggleDay(openExerciseDays, key)
const nutritionDays = computed(() => moduleValue('nutrition_plan').days || [])
const exerciseDays = computed(() => moduleValue('exercise_plan').days || [])
const pulmonaryDays = computed(() => moduleValue('pulmonary_rehab_plan').days || [])
const exerciseDerived = computed(() => moduleValue('exercise_plan').weekly_summary?.derived || {})
const exerciseCounts = [['正式有氧', 'formal_aerobic_days_actual'], ['功能活动', 'functional_activity_days_actual'], ['抗阻', 'resistance_days_actual'], ['柔韧', 'flexibility_days_actual'], ['恢复', 'recovery_days_actual']]
const pulmonaryActions = computed(() => { const seen = new Set(); return pulmonaryDays.value.flatMap((day) => day.actions || []).filter((action) => { const id = action.action_id || action.pulmonary_id || action.action_name; if (seen.has(id)) return false; seen.add(id); return true }) })
const actionName = (action) => action?.action_name || action?.name || action?.patient_display_name || '未命名动作'
const actionDose = (action) => { const dose = action?.dose; if (typeof dose === 'string' || typeof dose === 'number') return String(dose).replace(/\s*·\s*$/, ''); const values = [action?.dose_range, action?.candidate_dose, action?.duration_range, action?.reps_range, action?.repetitions != null ? `${action.repetitions} 次` : '', action?.sets != null ? `${action.sets} 组` : '', action?.intensity].filter((value) => typeof value === 'string' || typeof value === 'number').map((value) => String(value).replace(/\s*·\s*$/, '').trim()).filter(Boolean); return [...new Set(values)].join(' · ') || '剂量未提供' }
const actionStop = (action) => valueText(action?.stop_conditions || action?.precautions, '')
const exerciseRoleMap = { aerobic: 'FORMAL_AEROBIC', functional_activity: 'FUNCTIONAL_ACTIVITY', resistance: 'RESISTANCE', flexibility: 'FLEXIBILITY', recovery: 'RECOVERY' }
const exerciseActions = (day, key) => { if (Array.isArray(day?.[key])) return day[key]; const role = exerciseRoleMap[key]; return (day?.sessions || []).filter((session) => session?.session_role === role).flatMap((session) => session?.actions || []) }
const hasExerciseActions = (day) => Object.keys(exerciseRoleMap).some((key) => exerciseActions(day, key).length)
const mealItems = (meal) => meal?.food_items || meal?.items || []
const itemName = (item) => item?.dish_name || item?.food_name || item?.name || '未命名菜品'
const itemIngredients = (item) => item?.ingredients || item?.ingredient_items || []
const replacementItems = (item) => Array.isArray(item?.replacements) ? item.replacements : []
const replacementNeedsReview = (replacement) => String(replacement?.replacement_integrity?.status || '').toUpperCase() === 'FAIL'
const mealRealism = (meal) => { const realism = meal?.meal_realism; if (!realism) return ''; const validation = realism.meal_realism_validation; const failed = validation?.status && String(validation.status).toUpperCase() !== 'PASS' || validation?.pass === false || realism.household_execution_burden === 'HIGH'; return failed ? '本餐结构建议复核' : '' }
const isTechnicalMethod = (method) => /按V1\.3组件执行映射烹调|按组件映射执行|materialization|execution mapping|component execution mapping/i.test(String(method || ''))
const p05Text = (gate) => { if (gate?.selected) return displayLabel(gate?.mode, '术前技能学习'); const reason = gate?.reason ? displayLabel(gate.reason, '') : ''; return `有效咳嗽技能学习 · ${reason || '本周暂缓'}` }
const p06Text = (gate) => gate?.eligible ? '已安排' : '本周不安排'
const monitoringText = (module) => { const items = module?.items; if (!Array.isArray(items)) return reasonText(module) || '本周暂无监测安排'; return items.map((item) => typeof item === 'string' ? displayLabel(item) : item?.name || item?.label || item?.title || '').filter(Boolean).join('、') || reasonText(module) || '本周暂无监测安排' }
</script>

<template>
  <div class="clinician-plan-view">
    <article class="plan-section"><div class="section-heading-row"><h3>1. 患者概况与当前状态</h3><small>{{ statusText(moduleValue('patient_summary')) }}</small></div><div class="plan-stat-grid"><div><span>主方向</span><strong>{{ valueText(moduleValue('patient_summary').primary_nutrition_phenotype) }}</strong></div><div><span>复杂度叠加</span><strong>{{ valueText(moduleValue('patient_summary').complexity_overlay, '无') }}</strong></div><div><span>展示分型</span><strong>{{ valueText(moduleValue('patient_summary').display_phenotype) }}</strong></div><div><span>安全等级</span><strong>{{ valueText(moduleValue('patient_summary').safety_level) }}</strong></div></div><p class="plan-muted">手术窗口：{{ valueText(moduleValue('patient_summary').surgery_window) }} · 本周方向：{{ valueText(moduleValue('patient_summary').core_direction) }}</p></article>
    <article class="plan-section"><div class="section-heading-row"><h3>2. 评估摘要</h3><small>{{ statusText(moduleValue('assessment')) }}</small></div><p class="plan-muted">主方向：{{ valueText(moduleValue('assessment').primary_nutrition_phenotype) }} · 复杂度：{{ valueText(moduleValue('assessment').complexity_overlay, '无') }}</p><p v-if="moduleValue('assessment').missing_data?.length" class="plan-muted">待补充：{{ valueText(moduleValue('assessment').missing_data) }}</p><p v-if="moduleValue('assessment').uncertain_items?.length" class="plan-muted">待确认：{{ valueText(moduleValue('assessment').uncertain_items) }}</p></article>
    <article class="plan-section"><div class="section-heading-row"><h3>3. 本周管理目标</h3><small>{{ statusText(moduleValue('weekly_goals')) }}</small></div><div v-if="goalEntries(moduleValue('weekly_goals').items).length" class="goal-list"><p v-for="goal in goalEntries(moduleValue('weekly_goals').items)" :key="goal.key" class="goal-item"><strong>{{ goal.label }}</strong><span>{{ valueText(goal.value) }}</span></p></div><p v-else class="plan-muted">{{ reasonText(moduleValue('weekly_goals')) || '本周暂无独立目标' }}</p></article>
    <article class="plan-section"><div class="section-heading-row"><h3>4. 能量与营养依据</h3><small>{{ statusText(moduleValue('nutrition_basis').energy) }}</small></div><div class="plan-stat-grid"><div><span>能量状态</span><strong>{{ statusText(moduleValue('nutrition_basis').energy) }}</strong></div><div><span>候选能量</span><strong>{{ moduleValue('nutrition_basis').energy?.candidate_kcal != null ? `${moduleValue('nutrition_basis').energy.candidate_kcal} kcal/天` : '—' }}</strong></div><div><span>蛋白状态</span><strong>{{ statusText(moduleValue('nutrition_basis').protein) }}</strong></div><div><span>饮食模式</span><strong>{{ displayLabel(moduleValue('nutrition_basis').diet_generation_mode) }}</strong></div></div><p v-if="moduleValue('nutrition_basis').review_state?.required" class="plan-muted">需要医护复核当前营养依据。</p></article>
    <article class="plan-section diet-section"><div class="section-heading-row"><h3>5. 第一周饮食方案</h3><small>{{ statusText(moduleValue('nutrition_plan')) }}</small></div><div class="plan-summary-grid"><span>能量：{{ statusText(moduleValue('nutrition_basis').energy) }}</span><span>饮食模式：{{ displayLabel(moduleValue('nutrition_plan').diet_generation_mode || moduleValue('nutrition_basis').diet_generation_mode) }}</span></div><div v-for="(day, index) in nutritionDays" :key="`nutrition-${normalizeDayKey(day, index)}`" class="day-card"><button type="button" class="day-toggle" @click="toggleDietDay(normalizeDayKey(day, index))"><span>第{{ day.day || index + 1 }}天</span><span>{{ isDietDayOpen(normalizeDayKey(day, index)) ? '收起' : '展开' }}⌄</span></button><div v-if="isDietDayOpen(normalizeDayKey(day, index))" class="day-content"><div v-for="([mealKey, meal]) in Object.entries(day.meals || {})" :key="`${day.day || index}-${mealKey}`" class="meal-card"><div class="meal-title"><strong>{{ displayLabel(meal.meal || mealKey, '餐次') }}</strong><span v-if="meal.patient_meal_name || meal.meal_name">{{ meal.patient_meal_name || meal.meal_name }}</span></div><div v-for="item in mealItems(meal)" :key="item.food_item_id || item.component_id || itemName(item)" class="food-item"><strong>{{ itemName(item) }}</strong><div v-if="itemIngredients(item).length" class="ingredient-list"><span v-for="ingredient in itemIngredients(item)" :key="ingredient.ingredient_id || ingredient.ingredient_name">{{ ingredient.ingredient_name || ingredient.name || '食材' }} {{ ingredient.executable_amount ?? '—' }}{{ ingredient.unit || '' }}</span></div><p v-if="item.simple_method && !isTechnicalMethod(item.simple_method)" class="food-method">做法：{{ item.simple_method }}</p><p v-if="itemNutritionText(item)" class="food-nutrition">营养：{{ itemNutritionText(item) }}</p><div v-if="replacementItems(item).length" class="replacement-block"><strong>可替换方案</strong><div v-for="replacement in replacementItems(item)" :key="replacement.replacement_component_id || replacement.dish_name" class="replacement-card"><strong>{{ replacement.dish_name || '同类替换方案' }}</strong><div v-if="replacement.ingredients?.length" class="ingredient-list"><span v-for="ingredient in replacement.ingredients" :key="ingredient.ingredient_id || ingredient.ingredient_name">{{ ingredient.ingredient_name || ingredient.name || '食材' }} {{ ingredient.executable_amount ?? '—' }}{{ ingredient.unit || '' }}</span></div><p v-if="replacement.simple_method && !isTechnicalMethod(replacement.simple_method)" class="food-method">做法：{{ replacement.simple_method }}</p><p v-if="replacement.planned_nutrition" class="food-nutrition">营养：{{ nutritionText(replacement.planned_nutrition, '') }}</p><p v-if="replacementNeedsReview(replacement)" class="replacement-warning">替换方案需复核</p></div></div></div><p class="macro-line">本餐营养：{{ plannedNutritionText(meal) }}</p><p v-if="mealRealism(meal)" class="realism-line">{{ mealRealism(meal) }}</p></div></div></div></article>
    <article class="plan-section"><div class="section-heading-row"><h3>6. 第一周运动方案</h3><small>{{ statusText(moduleValue('exercise_plan')) }}</small></div><div class="plan-inline-values"><span v-for="([label, key]) in exerciseCounts" :key="key">{{ label }}：{{ exerciseDerived[key] ?? 0 }} 天</span></div><div v-for="(day, index) in exerciseDays" :key="`exercise-${normalizeDayKey(day, index)}`" class="day-card"><button type="button" class="day-toggle" @click="toggleExerciseDay(normalizeDayKey(day, index))"><span>第{{ day.day || index + 1 }}天</span><span>{{ isExerciseDayOpen(normalizeDayKey(day, index)) ? '收起' : '展开' }}⌄</span></button><div v-if="isExerciseDayOpen(normalizeDayKey(day, index))" class="day-content"><template v-for="group in [{ key: 'aerobic', label: '正式有氧' }, { key: 'functional_activity', label: '功能活动' }, { key: 'resistance', label: '抗阻' }, { key: 'flexibility', label: '柔韧' }, { key: 'recovery', label: '恢复' }]" :key="group.key"><section v-if="exerciseActions(day, group.key).length" class="exercise-category"><h4>{{ group.label }}</h4><div v-for="action in exerciseActions(day, group.key)" :key="action.action_id || action.exercise_id || action.action_name" class="prescription-card"><div><strong>{{ actionName(action) }}</strong><span>{{ actionDose(action) }}</span></div><p v-if="action.purpose">目的：{{ action.purpose }}</p><small v-if="actionStop(action)">停止：{{ actionStop(action) }}</small></div></section></template><p v-if="!hasExerciseActions(day)" class="plan-muted">本日不安排运动任务</p></div></div></article>
    <article class="plan-section"><div class="section-heading-row"><h3>7. 第一周肺预康复方案</h3><small>{{ statusText(moduleValue('pulmonary_rehab_plan')) }}</small></div><div v-for="action in pulmonaryActions" :key="action.action_id || action.pulmonary_id || action.action_name" class="prescription-card"><div><strong>{{ actionName(action) }}</strong><span>{{ actionDose(action) }}</span></div><p v-if="action.purpose">目的：{{ action.purpose }}</p><small v-if="actionStop(action)">停止：{{ actionStop(action) }}</small></div><p class="plan-muted">有效咳嗽技能学习：{{ p05Text(moduleValue('pulmonary_rehab_plan').p05_gate) }}</p><p class="plan-muted">辅助排痰设备训练：{{ p06Text(moduleValue('pulmonary_rehab_plan').p06_gate) }}</p></article>
    <article class="plan-section"><div class="section-heading-row"><h3>8. 监测与记录</h3><small>{{ statusText(moduleValue('monitoring')) }}</small></div><p>{{ monitoringText(moduleValue('monitoring')) }}</p></article>
    <article class="plan-section safety-section"><div class="section-heading-row"><h3>9. 安全/暂停/升级</h3><small>{{ valueText(moduleValue('safety').safety_level) }}</small></div><p>关注原因：{{ valueText(moduleValue('safety').reason_codes, '无') }}</p><p v-if="moduleValue('safety').stop_conditions">暂停条件：{{ moduleValue('safety').stop_conditions }}</p><p v-if="moduleValue('safety').precautions">注意事项：{{ moduleValue('safety').precautions }}</p><p v-if="moduleValue('safety').escalation">升级处理：{{ moduleValue('safety').escalation }}</p></article>
    <article class="plan-section"><div class="section-heading-row"><h3>10. Day7复评与下一周</h3><small>{{ statusText(moduleValue('weekly_review')) }}</small></div><p>{{ moduleValue('weekly_review').status === 'NOT_DUE' ? '尚未到第7天复评时间' : statusText(moduleValue('weekly_review')) }}</p><details v-if="moduleValue('weekly_review').raw_decision"><summary>查看复评状态</summary><p class="plan-muted">{{ displayLabel(moduleValue('weekly_review').raw_decision) }}</p></details></article>
    <article class="plan-section"><div class="section-heading-row"><h3>11. 医生审核与发布</h3><small>{{ reviewStatusText(moduleValue('clinician_review')) }}</small></div><p>审核状态：{{ reviewStatusText(moduleValue('clinician_review')) }}</p><p>临床安全：{{ valueText(moduleValue('safety').safety_level) }}</p><p v-if="moduleValue('clinician_review').publication_blockers?.length">发布原因：{{ valueText(moduleValue('clinician_review').publication_blockers) }}</p><p v-else>发布阻断：无</p><p>发布状态：{{ moduleValue('clinician_review').publication_blocked ? '暂不可发布' : '未阻断' }} · {{ publicationStatusText(moduleValue('clinician_review').publication_validation) }}</p><p v-if="moduleValue('clinician_review').audit?.artifact_manifest_status && String(moduleValue('clinician_review').audit.artifact_manifest_status).toUpperCase() !== 'PASS'" class="replacement-warning">方案材料需复核</p><slot name="actions"></slot></article>
  </div>
</template>

<style scoped>
.clinician-plan-view { display: grid; gap: 22px; }
.clinician-plan-view > .plan-section { padding: 22px; }
.clinician-plan-view .section-heading-row { margin-bottom: 16px; }
.clinician-plan-view .day-card { margin-top: 12px; }
.clinician-plan-view .day-content { gap: 12px; padding: 14px; }
.clinician-plan-view .meal-card, .clinician-plan-view .prescription-card { padding: 14px; }
.clinician-plan-view .clinician-plan-actions { display: grid; gap: 12px; margin-top: 16px; }
.clinician-plan-view .clinician-plan-actions .care-actions { gap: 10px; }
.plan-summary-grid { display: flex; flex-wrap: wrap; gap: 8px 18px; margin-bottom: 12px; color: #607b97; font-size: 13px; }
.goal-list { display: grid; gap: 10px; }
.goal-item { display: flex; justify-content: space-between; gap: 16px; padding: 10px 12px; border-radius: 9px; background: #f7faff; }
.goal-item strong { color: #315d8c; }
.goal-item span { color: #607b97; text-align: right; }
.meal-title { display: flex; justify-content: space-between; gap: 12px; margin-bottom: 10px; }
.meal-title span { color: #607b97; }
.food-item { display: grid; gap: 6px; margin-top: 12px; padding: 12px; border-radius: 8px; background: #fbfdff; }
.ingredient-list { display: flex; flex-wrap: wrap; gap: 6px 14px; color: #49647e; font-size: 13px; }
.food-method, .food-nutrition, .macro-line, .realism-line { margin: 0; color: #607b97; font-size: 13px; }
.replacement-block { display: grid; gap: 8px; margin-top: 6px; }
.replacement-card { display: grid; gap: 5px; padding: 9px 11px; border-left: 3px solid #9abbd8; background: #f4f8fc; }
.replacement-warning { margin: 0; color: #8b5a20; font-size: 13px; }
</style>
