// Assessment Questionnaire V1.2 唯一前端字段配置。
// Q1-Q4 是 patient 账号资料的只读关联，不在评估页重复采集；仍保留题号，
// 以便患者端、医护端、历史版本和 API 映射统一为 Q1-Q56。
const q = (questionId, label, type = 'text', extra = {}) => ({ questionId, label, type, required: false, patientVisible: true, clinicianVisible: true, ...extra })
const profileRef = (questionId, label, profileKey) => q(questionId, label, 'profile_ref', { key: `profile_${profileKey}`, profileKey, source: 'patient_profile', patientVisible: false, clinicianVisible: true, countsForProgress: true })

export const assessmentVersion = '1.2'

export const assessmentSections = [
  { id: 'basic-preop', title: '基础信息与术前情况', subtitle: '身份信息来自账号资料；此处补充居住照护和手术时间窗口', icon: '01', fields: [
    profileRef(1, '姓名', 'name'), profileRef(2, '性别', 'sex'), profileRef(3, '出生年月日', 'birthDate'), profileRef(4, '联系方式', 'phone'),
    q(5, '居住照护情况', 'radio', { key: 'q5_living', options: ['独居', '家人共同居住', '其他'], otherKey: 'q5_livingOther' }), q(6, '预计多久接受肺结节手术？', 'radio', { key: 'q6_surgeryWindow', options: ['2周以内', '2–4周', '4–8周', '8周以上', '未确定'] }),
  ] },
  { id: 'nodule-respiratory', title: '肺结节与呼吸情况', subtitle: '结节基本信息、影像表现和呼吸症状', icon: '02', fields: [
    q(7, '肺结节数量', 'radio', { key: 'q7_noduleCount', options: ['单发', '多发'] }), q(8, '最大径', 'number', { key: 'q8_maxDiameter', unit: 'mm' }), q(9, '部位', 'radio', { key: 'q9_location', options: ['左上', '左下', '右上', '右中', '右下'] }), q(10, '结节类型', 'radio', { key: 'q10_noduleType', options: ['纯磨玻璃', '部分实性', '实性', '不清楚'] }),
    q(11, '是否存在以下影像表现', 'checkbox', { key: 'q11_imagingSigns', options: ['毛刺', '分叶', '胸膜牵拉', '血管集束', '空泡征', '无', '其他'], otherKey: 'q11_imagingOther' }), q(12, '呼吸系统症状', 'checkbox', { key: 'q12_respiratorySymptoms', options: ['无', '咳嗽', '咳痰', '咯血', '胸闷', '胸痛', '活动气促', '静息气促', '其他'], otherKey: 'q12_respiratoryOther' }), q(13, '既往穿刺 / 活检 / 相关治疗', 'radio', { key: 'q13_priorTreatment', options: ['有', '无'], noteKey: 'q13_priorTreatmentNote', noteWhen: ['有'], notePlaceholder: '请补充说明既往穿刺、活检或相关治疗' }),
  ] },
  { id: 'body-function', title: '身体测量与功能', subtitle: '身体基础测量、体成分和6分钟步行试验', icon: '03', fields: [
    q(14, '身高', 'number', { key: 'q14_height', unit: 'cm' }), q(15, '体重', 'number', { key: 'q15_weight', unit: 'kg' }), q(16, '腰围', 'number', { key: 'q16_waist', unit: 'cm' }), q(17, '小腿围', 'number', { key: 'q17_calf', unit: 'cm' }), q(18, '体脂率', 'number', { key: 'q18_bodyFat', unit: '%' }), q(19, '肌肉量', 'number', { key: 'q19_muscleMass', unit: 'kg（以设备为准）' }), q(20, '内脏脂肪', 'number', { key: 'q20_visceralFat', unit: '等级/数值' }), q(21, '水分率', 'number', { key: 'q21_waterRate', unit: '%' }), q(22, '基础代谢', 'number', { key: 'q22_bmr', unit: 'kcal/day' }), q(23, '脂肪量', 'number', { key: 'q23_fatMass', unit: 'kg' }), q(24, '骨骼肌量', 'number', { key: 'q24_skeletalMuscle', unit: 'kg' }), q(25, '蛋白质率', 'number', { key: 'q25_proteinRate', unit: '%' }), q(26, 'SMI', 'number', { key: 'q26_smi', unit: 'kg/m²' }),
    q(27, '6分钟步行试验', 'composite', { key: 'q27_walkTest', optional: true, subfields: [{ key: 'distance', label: '距离', type: 'number', unit: 'm' }, { key: 'heartRate', label: '心率范围', type: 'text', placeholder: '例如 78–96' }, { key: 'spo2', label: '血氧范围', type: 'text', placeholder: '例如 96–99%' }, { key: 'borg', label: 'BORG评分变化', type: 'text', placeholder: '请输入评分变化' }] }),
  ] },
  { id: 'nutrition-diet', title: '营养与饮食', subtitle: '近期体重变化、进食情况、过敏和饮食结构', icon: '04', fields: [
    q(28, '最近6个月体重变化', 'radio', { key: 'q28_weightChange', options: ['稳定', '主动减重', '主动增重', '不明原因下降', '不明原因增加'] }), q(29, '食欲', 'radio', { key: 'q29_appetite', options: ['正常', '下降', '明显下降', '增加'] }), q(30, '进食量', 'radio', { key: 'q30_intake', options: ['正常', '减少25%', '减少50%', '几乎无法进食'] }), q(31, '有无进食困难', 'checkbox', { key: 'q31_eatingDifficulties', options: ['早饱', '恶心', '呕吐', '腹胀', '腹泻', '便秘', '吞咽困难', '咀嚼困难', '反流', '无', '其他'], otherKey: 'q31_eatingOther' }), q(32, '食物过敏', 'checkbox', { key: 'q32_foodAllergy', options: ['无', '牛奶', '鸡蛋', '海鲜', '坚果', '花生', '其他'], otherKey: 'q32_foodAllergyOther' }), q(33, '食物不耐受', 'checkbox', { key: 'q33_foodIntolerance', options: ['乳糖不耐', '麸质', '无', '其他'], otherKey: 'q33_foodIntoleranceOther' }), q(34, '饮食结构', 'checkbox', { key: 'q34_dietPattern', options: ['三餐规律', '经常不吃早餐', '外卖多', '高油', '高盐', '甜食多', '饮料多', '蔬菜少', '蛋白质不足', '宵夜', '暴饮暴食', '长期节食', '其他'], otherKey: 'q34_dietOther' }),
  ] },
  { id: 'lifestyle', title: '运动、睡眠与生活方式', subtitle: '日常运动、睡眠、吸烟和饮酒情况', icon: '05', fields: [
    q(35, '目前运动频率', 'radio', { key: 'q35_exerciseFrequency', options: ['无', '<1次/周', '1–2次/周', '≥3次/周'] }), q(36, '运动类型', 'checkbox', { key: 'q36_exerciseTypes', options: ['步行', '力量训练', '太极', '骑车', '游泳', '其他'], otherKey: 'q36_exerciseOther' }), q(37, '活动限制', 'checkbox', { key: 'q37_activityLimits', options: ['膝痛', '腰痛', '肩痛', '气促', '疲劳', '头晕', '平衡差', '害怕运动', '无', '其他'], otherKey: 'q37_activityOther' }), q(38, '睡眠时间', 'radio', { key: 'q38_sleepDuration', options: ['<6小时', '6–7小时', '7–8小时', '>8小时'] }), q(39, '睡眠', 'radio', { key: 'q39_sleepQuality', options: ['正常', '熬夜', '夜班'] }), q(40, '鼾症', 'radio', { key: 'q40_snoring', options: ['无', '有', '已诊断OSA'] }), q(41, '吸烟', 'radio', { key: 'q41_smoking', options: ['从不', '已戒', '现在吸'] }), q(42, '饮酒', 'radio', { key: 'q42_alcohol', options: ['不饮', '偶尔', '每周', '经常'] }),
  ] },
  { id: 'disease-labs', title: '疾病、生命体征与关键化验', subtitle: '代谢疾病筛查、生命体征和关键实验室指标', icon: '06', fields: [
    q(43, '代谢疾病筛查', 'checkbox', { key: 'q43_metabolicConditions', options: ['高血压', '糖尿病', '糖耐量异常', '血脂异常', '脂肪肝', '高尿酸', '痛风', '心血管疾病', '肾病', '甲状腺疾病', '睡眠呼吸暂停', '无', '其他'], otherKey: 'q43_metabolicOther' }), q(44, '生命体征', 'composite', { key: 'q44_vitals', subfields: [{ key: 'systolic', label: '收缩压', type: 'number', unit: 'mmHg' }, { key: 'diastolic', label: '舒张压', type: 'number', unit: 'mmHg' }, { key: 'heartRate', label: '心率', type: 'number', unit: '次/分' }, { key: 'spo2', label: 'SpO₂', type: 'number', unit: '%' }] }), q(45, '关键化验指标', 'labs', { key: 'q45_labs', dateKey: 'q45_checkDate', optional: true, labs: [['glucose', '血糖', 'mmol/L'], ['hba1c', 'HbA1c', '%'], ['tg', 'TG', 'mmol/L'], ['ldlc', 'LDL-C', 'mmol/L'], ['hdlc', 'HDL-C', 'mmol/L'], ['uricAcid', '尿酸', 'μmol/L'], ['alt', 'ALT', 'U/L'], ['albumin', '白蛋白', 'g/L'], ['creatinine', '肌酐', 'μmol/L'], ['egfr', 'eGFR', 'mL/min/1.73m²'], ['hemoglobin', '血红蛋白', 'g/L'], ['tsh', 'TSH', 'mIU/L'], ['vitaminD', '维生素D', 'ng/mL']] }),
  ] },
  { id: 'treatment-execution', title: '用药、治疗、执行能力与患者偏好', subtitle: '记录现状、可能的执行障碍与偏好', icon: '07', fields: [
    q(46, '目前用药类别', 'checkbox', { key: 'q46_medicationCategories', options: ['降压药', '降糖药', '胰岛素', '调脂药', '降尿酸药', 'GLP-1药物', '激素', '甲状腺药', '无', '其他'], otherKey: 'q46_medicationOther' }), q(47, '药物详情', 'repeaters', { key: 'q47_medications', optionalWhen: { key: 'q46_medicationCategories', includes: '无' }, itemLabel: '药物', fields: [['name', '药物名称', 'text'], ['dose', '剂量', 'text'], ['frequency', '频次', 'text'], ['time', '固定时间', 'text'], ['adjusted', '近期是否调整', 'radio', ['是', '否']]] }), q(48, '治疗类型', 'checkbox', { key: 'q48_treatmentTypes', options: ['营养治疗', '康复训练', '理疗', '针灸', '埋线', '无', '其他'], otherKey: 'q48_treatmentOther' }), q(49, '治疗项目详情', 'repeaters', { key: 'q49_treatments', optionalWhen: { key: 'q48_treatmentTypes', includes: '无' }, itemLabel: '治疗项目', fields: [['name', '治疗项目名称', 'text'], ['date', '时间', 'date'], ['frequency', '频次', 'text'], ['course', '疗程', 'text'], ['familyHelp', '是否需要家属协助', 'radio', ['是', '否']]] }),
    q(50, '肝弹性成像', 'liver_elasticity', { key: 'q50_liverElastography', optional: true, fields: [{ key: 'performed', label: '是否做过', type: 'radio', options: ['否', '是'] }, { key: 'checkDate', label: '检查日期', type: 'date' }, { key: 'method', label: '检查方式', type: 'radio', options: ['FibroScan', 'SWE/SWM', 'MRE', '不清楚'] }, { key: 'lsm', label: '肝脏硬度值 LSM', type: 'number', unit: 'kPa' }, { key: 'conclusion', label: '报告结论', type: 'radio', options: ['正常/无明显纤维化', '轻度/早期纤维化', '显著/进展期纤维化', '提示肝硬化', '报告未明确/不清楚'] }, { key: 'fatQuantType', label: '脂肪定量', type: 'radio', options: ['无', 'CAP', '其他指标'] }, { key: 'cap', label: 'CAP', type: 'number', unit: 'dB/m' }, { key: 'otherFatIndex', label: '其他脂肪定量指标', type: 'text' }] }),
    q(51, '哪些情况可能影响您完成健康管理计划？', 'checkbox', { key: 'q51_executionBarriers', options: ['工作忙', '时间少', '不会做饭', '外卖多', '不知道怎么吃', '不知道怎么运动', '疼痛限制', '家人不支持', '不会操作设备', '不想改变', '其他'], otherKey: 'q51_executionOther' }), q(52, '患者偏好：饮食记录', 'radio', { key: 'q52_dietRecordMethod', options: ['称重', '拍照', '家庭估算'] }), q(53, '运动偏好', 'radio', { key: 'q53_exercisePreference', options: ['室内', '户外', '居家', '健身房'] }), q(54, '家属协助', 'radio', { key: 'q54_familySupport', options: ['不需要', '饮食帮助', '运动帮助', '全程参与'] }),
  ] },
  { id: 'health-goals', title: '健康目标', subtitle: '您希望在健康管理中重点改善什么？', icon: '08', fields: [
    q(55, '健康目标', 'checkbox', { key: 'q55_healthGoals', options: ['减脂', '控糖', '降脂', '降尿酸', '增肌', '增重', '改善营养', '提高运动能力', '改善肺功能', '戒烟', '为手术准备'] }),
    q(56, '本阶段术前健康管理目标', 'q56_goal', { key: 'q56_goal', optional: true, clinicianGuided: true }),
  ] },
]

export const assessmentQuestionList = assessmentSections.flatMap((section) => section.fields)
export const assessmentQuestionCount = assessmentQuestionList.length
export function getSection(id) { return assessmentSections.find((section) => section.id === id) || assessmentSections[0] }
