<script setup>
import { computed, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { dailyRecordData, saveDailyRecord } from '../../stores/patientStore'
const existing = computed(() => dailyRecordData().diet || {})
const meals = [['breakfast', '早餐'], ['lunch', '午餐'], ['dinner', '晚餐']]
const form = reactive({ date: existing.value.date || new Date().toISOString().slice(0, 10), breakfast: existing.value.breakfast || '', lunch: existing.value.lunch || '', dinner: existing.value.dinner || '', completion: existing.value.completion || {}, protein: existing.value.protein || {}, replaced: existing.value.replaced || '否', replacementDetail: existing.value.replacementDetail || '', extra: existing.value.extra || '无', appetite: existing.value.appetite || '', barrier: existing.value.barrier || '', overall: existing.value.overall || '', note: existing.value.note || '', images: existing.value.images || [] })
const saved = ref(Boolean(existing.value.status))
function onFiles(event, meal) { form.images = [...form.images, ...Array.from(event.target.files || []).map((file) => `${meal}：${file.name}`)]; event.target.value = '' }
  async function save() { const complete = meals.every(([key]) => form[key]); const result = await saveDailyRecord('diet', { ...form, status: complete ? 'completed' : 'pending', label: complete ? '三餐已记录' : '部分待记录' }); saved.value = Boolean(result?.ok); window.alert(result?.ok ? '饮食记录已保存' : '网络异常，饮食记录待同步，请稍后重试') }
</script>
<template><section class="patient-page record-detail-page"><div class="page-title-mobile"><RouterLink to="/patient/records" class="back-link">‹</RouterLink><div><p class="eyebrow">P-04-02 · 每日打卡</p><h1>饮食记录</h1></div></div><section class="mobile-card record-form-card"><div class="form-field"><label>日期</label><input v-model="form.date" type="date" /></div><div v-for="meal in meals" :key="meal[0]" class="meal-block"><div class="meal-head"><label>{{ meal[1] }}</label><label class="photo-button">上传图片（辅助）<input type="file" accept="image/*" @change="onFiles($event, meal[1])" /></label></div><textarea v-model="form[meal[0]]" :placeholder="`记录${meal[1]}吃了什么`"></textarea><div class="form-row-two"><label>完成比例<select v-model="form.completion[meal[0]]"><option value="">未填写</option><option>100</option><option>75</option><option>50</option><option>25</option><option>almost_none</option></select></label><label>主蛋白完成<select v-model="form.protein[meal[0]]"><option value="">未填写</option><option>all</option><option>most</option><option>half</option><option>little</option><option>none</option></select></label></div></div><div class="form-row-two"><label>是否替换食物<select v-model="form.replaced"><option>否</option><option>是</option></select></label><label>计划外摄入<select v-model="form.extra"><option>无</option><option>含糖饮料</option><option>零食</option><option>水果</option><option>其他</option></select></label></div><input v-if="form.replaced === '是' || form.extra === '其他'" v-model="form.replacementDetail" class="other-input" placeholder="请填写替换或额外摄入内容" /><div class="form-row-two"><label>食欲（0–10）<input v-model="form.appetite" type="number" min="0" max="10" /></label><label>总体完成方案<select v-model="form.overall"><option value="">未填写</option><option>≥90%</option><option>75–89%</option><option>50–74%</option><option>&lt;50%</option></select></label></div><div class="form-field"><label>进食障碍/备注</label><textarea v-model="form.barrier" placeholder="早饱、恶心、腹胀等"></textarea><textarea v-model="form.note" placeholder="可补充说明"></textarea></div><p class="record-hint">图片只保存和查看，不自动识别热量；实际摄入以计划值、完成比例和替换记录综合评估。</p><button class="primary-mobile full-button" type="button" @click="save">保存今日饮食</button></section><section class="mobile-card"><p class="eyebrow">今日完成状态</p><div class="record-status-card" :class="saved ? 'completed' : 'pending'"><strong>{{ saved ? '已保存' : '尚未记录' }}</strong><span>{{ form.images.length ? `已上传${form.images.length}张图片` : '可上传三餐图片' }}</span></div></section></section></template>
