<script setup>
import { computed, reactive } from 'vue'
import { RouterLink } from 'vue-router'
import { currentPatient, dailyRecordData, saveDailyRecord } from '../../stores/patientStore'
import { api } from '../../api/client'
const record = computed(() => dailyRecordData().body || {})
const form = reactive({ date: record.value.date || new Date().toISOString().slice(0, 10), weight: record.value.weight || '', bodyFat: record.value.bodyFat || '', waist: record.value.waist || '', muscleMass: record.value.muscleMass || '', skeletalMuscle: record.value.skeletalMuscle || '', waterRate: record.value.waterRate || '', waterAmount: record.value.waterAmount || '', fatMass: record.value.fatMass || '', proteinRate: record.value.proteinRate || '', bmr: record.value.bmr || '', visceralFat: record.value.visceralFat || '' })
const mockHistory = [{ date: '2026-09-03', weight: '68.4', bodyFat: '31.2', waist: '89' }, { date: '2026-09-01', weight: '68.8', bodyFat: '31.5', waist: '90' }, { date: '2026-08-29', weight: '69.1', bodyFat: '31.8', waist: '91' }]
const history = computed(() => [...(record.value.history || []), ...mockHistory].filter((item, index, list) => list.findIndex((entry) => entry.date === item.date) === index).slice(0, 7))
async function save() { const entry = { ...form }; const result = await saveDailyRecord('body', { ...entry, history: [entry, ...(record.value.history || [])].slice(0, 7) }); try { await api.createMeasurement(currentPatient.value.id, { record_date: form.date, weight_kg: Number(form.weight) || null, body_fat_pct: Number(form.bodyFat) || null, waist_cm: Number(form.waist) || null, note: JSON.stringify({ muscleMass: form.muscleMass, skeletalMuscle: form.skeletalMuscle, waterRate: form.waterRate, waterAmount: form.waterAmount, fatMass: form.fatMass, proteinRate: form.proteinRate, bmr: form.bmr, visceralFat: form.visceralFat }) }); window.alert('身体数据已保存') } catch { window.alert('网络异常，身体数据未写入医生端，请稍后重试') } }
</script>
<template><section class="patient-page record-detail-page"><div class="page-title-mobile"><RouterLink to="/patient/records" class="back-link">‹</RouterLink><div><p class="eyebrow">P-04-01 · 每日打卡</p><h1>身体数据记录</h1></div></div><section class="mobile-card record-form-card"><div class="form-field"><label>日期</label><input v-model="form.date" type="date" /></div><div class="form-field"><label>体重（kg）</label><input v-model="form.weight" type="number" step="0.1" placeholder="请输入今日体重" /></div><div class="form-field"><label>体脂率（%）</label><input v-model="form.bodyFat" type="number" step="0.1" placeholder="设备可提供时填写" /></div><div class="form-field"><label>腰围（cm）</label><input v-model="form.waist" type="number" step="0.1" placeholder="按方案要求每周记录" /></div><div class="form-row-two"><div class="form-field"><label>肌肉量（kg）</label><input v-model="form.muscleMass" type="number" step="0.1" placeholder="设备可提供时填写" /></div><div class="form-field"><label>骨骼肌量（kg）</label><input v-model="form.skeletalMuscle" type="number" step="0.1" /></div></div><div class="form-row-two"><div class="form-field"><label>水分率（%）</label><input v-model="form.waterRate" type="number" step="0.1" /></div><div class="form-field"><label>水分量</label><input v-model="form.waterAmount" type="number" step="0.1" /></div></div><div class="form-row-two"><div class="form-field"><label>脂肪量（kg）</label><input v-model="form.fatMass" type="number" step="0.1" /></div><div class="form-field"><label>蛋白质率（%）</label><input v-model="form.proteinRate" type="number" step="0.1" /></div></div><div class="form-row-two"><div class="form-field"><label>BMR（辅助值）</label><input v-model="form.bmr" type="number" step="1" /></div><div class="form-field"><label>内脏脂肪</label><input v-model="form.visceralFat" type="number" step="0.1" /></div></div><p class="record-hint">建议晨起、排空、空腹，在相近时间和条件下测量。设备截图仅作辅助，不替代医护判断。</p><button class="primary-mobile full-button" type="button" @click="save">保存今日数据</button></section><section class="mobile-card"><div class="card-title-row"><div><p class="eyebrow">最近记录</p><h2>已保存的数据</h2></div><span class="trend-filter">共{{ history.length }}条</span></div><div v-if="history.length" class="history-list"><div v-for="item in history" :key="item.date" class="history-row"><strong>{{ item.date }}</strong><span>体重 {{ item.weight || '—' }}kg · 体脂 {{ item.bodyFat || '—' }}% · 腰围 {{ item.waist || '—' }}cm</span></div></div><p v-else class="empty-copy">暂无记录，保存今日数据后会显示在这里。</p></section></section></template>
